sudo: required

language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

env:
  global:
    - AWS_ACCESS_KEY_ID=foo
    - AWS_SECRET_ACCESS_KEY=bar
    - SQS_QUEUE_URL=http://localhost:9324/queue/queue1

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

services:
  - docker

install:
  - docker run -d -p 9324:9324 s12v/elasticmq
  - sbt clean update

before_script:
  - bash <(curl -s https://raw.githubusercontent.com/s12v/wait4port/master/wait4port.sh) http://localhost:9324

script:
  - sbt coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
